name: Deploy to Alibaba Cloud

on:
  push:
    branches:
      - main  # Robot akan jalan otomatis kalau ada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Executing SSH commands to deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/omdb-search
            # 1. Tarik kode terbaru dari GitHub
            git fetch --all
            git reset --hard origin/main
            git config --global --add safe.directory /var/www/omdb-search
            
            # 2. Hapus paksa container yang sering bikin bug 'ContainerConfig'
            # Kita hapus manual supaya docker-compose tidak bingung saat 'recreating'
            docker rm -f omdb-nginx || true
            
            # 3. Nyalakan ulang stack-nya
            docker-compose up -d
