name: Deploy to Alibaba Cloud

on:
  push:
    branches:
      - main  # Robot akan jalan otomatis kalau ada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Executing SSH commands to deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/omdb-search
            # Ambil kode terbaru
            git fetch --all
            git reset --hard origin/main
            git config --global --add safe.directory /var/www/omdb-search

            # Kita gunakan cara 'Restart Total' agar tidak kena bug 'ContainerConfig'
            # Kita panggil docker compose (Space) yang sudah kita instal tadi
            docker compose down || true
            docker compose up -d --force-recreate
